#!/bin/bash

# This will rename the provided file(s) to .sav (cascading .s01, .s02, etc), and make a new copy of the file with the original name.
# If the -x parameter is provided, it will not make a new copy of the file.




